# Generated by Django 4.1 on 2022-10-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('1', 'foundation'), ('2', 'non-governmental organisation'), ('3', 'local fundraising')], default='1', max_length=200)),
                ('categories', models.ManyToManyField(related_name='institutions', to='home.category')),
            ],
        ),
    ]
